source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'git'

cookbook 'users'
cookbook 'sudo'
cookbook 'chef-solo-search'

cookbook 'docker'
cookbook 'redisio'
cookbook 'phantomjs'
cookbook 'java'

cookbook 'nginx', git: 'https://github.com/miketheman/nginx.git'
#cookbook 'mesos'
#cookbook 'etcd'
cookbook 'postgresql', '~> 3.4.18'
cookbook 'yum-mysql-community', git: 'https://github.com/chef-cookbooks/yum-mysql-community.git'
#cookbook 'mysql', '= 5.6.3' #doesn't work
#cookbook 'nexus'
cookbook 'hadoop'
cookbook 'tomcat'
cookbook 'nagios'
#cookbook 'couchdb'
