source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'git'

cookbook 'users'
cookbook 'sudo'
cookbook 'chef-solo-search'

cookbook 'docker'
cookbook 'redisio'
cookbook 'phantomjs'
cookbook 'java'

#cookbook 'mesos'
#cookbook 'etcd'
cookbook 'postgresql', '~> 3.4.18'
#cookbook 'mysql', '= 5.6.3'
#cookbook 'ngnix'
#cookbook 'nexus'
cookbook 'hadoop'
#cookbook 'tomcat'
#cookbook 'nagios'
#cookbook 'couchdb'
